### PR TITLE
Various fondue fixes

### LINKED ISSUE #217: Encourage folks to contact me when the font fails
In the "oops couldn't handle that font" message.

### PR DESCRIPTION
**Pull request by RoelN**
Addresses some minor things

Fixes #217

### CODE REVIEW

File: src/components/FileDrop.vue [hunk 1]
```diff
@@ -9,18 +9,19 @@
...
 					class="button on"
 					@click="$emit('getExampleFont', 'GimletVariable-VF.woff2')"
 				>
-					Try with Gimlet!
+					Try with Gimlet
 				</button>
 				<span class="errormessage" :class="{ show: error }">
-					Oops! I couldn't handle that file.
+					<strong>Oops! I couldn't handle that file.</strong>
+					<a href="mailto:brokenfonts@pixelambacht.nl"
```
Comment (Ryuno-Ki) [inline src/components/FileDrop.vue:22]: You can even [populate subject and body](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content/Creating_links#email_links) if you want.

https://mailtolink.me/?ref=tiny-helpers via https://tiny-helpers.dev/email/ might come in handy (they lack the `?` before subject from what I can see)

File: src/components/FileDrop.vue [hunk 2]
```diff
@@ -141,14 +143,19 @@ export default {
 .errormessage {
 	margin-top: 1.25rem;
 	color: var(--red);
```
Comment (Ryuno-Ki) [inline src/components/FileDrop.vue:145]: Instead of `--red` the _meaning_ is preferred (i.e. `--error`). Unrelated in this PR.

**Review by Ryuno-Ki — COMMENTED** [review]
Some ideas to improve the status quo further.

File: src/components/FileDrop.vue (hunk 2 above)
Comment (RoelN) [reply src/components/FileDrop.vue:145]: I would normally not describe a variable like that, indeed, but since these are _the_ Wakamai Fondue Brand Colors™ I found it acceptable to use 'em like this!
